name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: dart test --file-reporter json:test.json
      - run: pwd
      - run: cat test.json
      - name: Show GitHub context   
          env: 
            GITHUB_CONTEXT: ${{ toJson(github) }}   
          run: echo "$GITHUB_CONTEXT" ``
      - run: pip3 install openpyxl
      - run: python3 check.py